### ISSUE TITLE
Github Enterprise Server - DR Backup and Restore

### ISSUE THREAD

**Issue by mabbashm110** [github/backup-utils#1088]
# Github Enterprise Server - Disaster Recovery (DR) Scenarios

## Description
I am evaluating Disaster Recovery (DR) scenarios for a Github Enterprise Server. The current setup is a standalone server with backup utilities installed on an Ubuntu machine. During the evaluation process, I encountered issues with the MSSQL backup and restore, which resulted in errors. Below are the details of the setup and the encountered errors.

## Setup Details
- Primary Github Server (v3.9.0): 
  - IP: 10.0.0.6
  - OS: Debian
  - Storage: Using Azure Storage for Actions and Blob as connection strings, tested and verified

- Backup Utilities Server (v3.9.0):
  - IP: 10.0.0.8
  - OS: Ubuntu
  - Tools: All necessary backup utilities installed

- New Github Server to Restore (v3.9.0):
  - IP: 10.0.0.9
  - OS: Debian

## Backup Configuration File
```markdown
# GitHub Enterprise Server backup configuration file

# The hostname of the GitHub Enterprise Server appliance to back up. The host
# must be reachable via SSH from the backup host.
GHE_HOSTNAME="10.0.0.6"

# Path to where backup data is stored. By default this is the "data"
# directory next to this file but can be set to an absolute path
# elsewhere for backing up to a separate partition / mount point.
GHE_DATA_DIR="data"

# The number of backup snapshots to retain. Old snapshots are pruned after each
# successful ghe-backup run. This option should be tuned based on the frequency
# of scheduled backup runs. If backups are scheduled hourly, snapshots will be
# available for the past N hours; if backups are scheduled daily, snapshots will
# be available for the past N days ...
GHE_NUM_SNAPSHOTS=10

# The hostname of the GitHub appliance to restore. If you've set up a separate
# GitHub appliance to act as a standby for recovery, specify its IP or hostname
# here. The host to restore to may also be specified directly when running
# ghe-restore so use of this variable isn't strictly required.
GHE_RESTORE_HOST="10.0.0.9"

# If set to 'yes', ghe-restore will omit the restore of audit logs.
#GHE_RESTORE_SKIP_AUDIT_LOGS=no

# When verbose output is enabled with `-v`, it's written to stdout by default. If
# you'd prefer it to be written to a separate file, set this option.
GHE_VERBOSE_LOG="/var/log/backup-verbose.log"

# Any extra options passed to the SSH command.
# In a single instance environment, nothing is required by default.
# In a clustering environment, "-i abs-path-to-ssh-private-key" is required.
#GHE_EXTRA_SSH_OPTS=""

# Any extra options passed to the rsync command. Nothing required by default.
#GHE_EXTRA_RSYNC_OPTS=""

# If set to 'no', GHE_DATA_DIR will not be created automatically
# and restore/backup will exit 8
#GHE_CREATE_DATA_DIR=yes

# If set to 'yes', git fsck will run on the repositories
# and print some additional info.
# WARNING: do not enable this, only useful for debugging/development
#GHE_BACKUP_FSCK=no

# Cadence of MSSQL backups
# <full>,<differential>,<transactionlog> all in minutes
# e.g.
#   - Full backup every week (10080 minutes)
#   - Differential backup every day (1440 minutes)
#   - Transactionlog backup every 15 minutes
#GHE_MSSQL_BACKUP_CADENCE=10080,1440,15

# If set to 'yes', ghe-backup jobs will run in parallel. Defaults to 'no'.
GHE_PARALLEL_ENABLED=yes

# Sets the maximum number of jobs to run in parallel. Defaults to the number
# of available processing units on the machine.
#GHE_PARALLEL_MAX_JOBS=2

# Sets the maximum number of rsync jobs to run in parallel. Defaults to the
# configured GHE_PARALLEL_MAX_JOBS, or the number of available processing 
# units on the machine.
# GHE_PARALLEL_RSYNC_MAX_JOBS=3

# When jobs are running in parallel wait as needed to avoid starting new jobs
# when the system's load average is not below the specified percentage. Defaults to
# unrestricted.
#GHE_PARALLEL_MAX_LOAD=50

# When running an external mysql database, run this script to trigger a MySQL backup
# rather than attempting to backup via backup-utils directly.
#EXTERNAL_DATABASE_BACKUP_SCRIPT="/bin/false"

# When running an external mysql database, run this script to trigger a MySQL restore
# rather than attempting to backup via backup-utils directly.
#EXTERNAL_DATABASE_RESTORE_SCRIPT="/bin/false"

# ...
```

## Encountered Errors during Backup
```
2023-08-01T05:06:41Z  ERROR  ghe-export-mssql is not available
```

## Encountered Errors during Restore - First Run
```
2023-08-01T04:47:17Z  ERROR  10.0.0.9:122 must have GitHub Actions enabled before restoring since the snapshot contains Actions data. Aborting. 
 Setup details for enabling Actions can be found here: https://docs.github.com/en/enterprise-server@/admin/github-actions/advanced-configuration-and-troubleshooting/backing-up-and-restoring-github-enterprise-server-with-github-actions-enabled
```

## Encountered Errors during Restore - Second Run
```
2023-08-01T05:30:01Z  ERROR  10.0.0.9:122 has Actions Cache service enabled but no Actions Cache data is present in the snapshot to restore. Aborting. 
 Please disable Actions cache service in 10.0.0.9:122 and retry.
 To disable Actions Cache service run as admin: ghe-actions-cache-disable
```

## Encountered Errors during Restore - Third Run
```
2023-08-01T06:17:02Z  INFO  Restoring Actions data ...
Error occurred while executing servicing step 'Repair Database Logins' for component RepairDatabaseLogins during RepairDatabaseLogins: The database is not correctly configured. Contact your GitHub Actions Server administrator.
   at Microsoft.TeamFoundation.Framework.Server.ServicingContext.FinishStep(Exception exception) in /mnt/_work/1/s/Vssf/Sdk/Server/Servicing/ServicingContext.cs:line 1074
   ...

Inner[1]: Microsoft.Data.SqlClient.SqlException
The EXECUTE permission was denied on the object 'prc_GetServiceVersion', database 'Mps_Configuration', schema 'dbo'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   ...
```

## Resolution Steps Taken
1. For First Restore Run: Followed the article: [Backing up and Restoring Github Enterprise Server with Github Actions Enabled](https://docs.github.com/en/enterprise-server@3.9/admin/github-actions/advanced-configuration-and-troubleshooting/back
2. For second Restore Run: I disabled Actions cache

**Comment by mabbashm110** [comment]
## Quick Update

I used the updated version of backup utils and it worked with an Elastic search exception.

## New Note

I have updated the Github servers to 3.9.2

Memory total/used/free+share/buff/cache: 15940/337/13912+3/1689/15287

```bash
2023-08-02T04:40:18Z  INFO  Backing up GitHub settings ...
2023-08-02T04:40:21Z  INFO  Backing up SSH authorized keys ...
2023-08-02T04:40:21Z  INFO  Backing up SSH host keys ...
2023-08-02T04:40:22Z  INFO  Backing up MySQL database using binary backup strategy ...
2023-08-02T04:40:37Z  INFO  Backing up MSSQL databases ...
2023-08-02T04:41:53Z  INFO  Backing up Actions data ...
2023-08-02T04:41:53Z  INFO  Backing up Minio data ...
2023-08-02T04:41:54Z  INFO  Backing up Redis database ...
2023-08-02T04:41:54Z  INFO  Backing up audit log ...
2023-08-02T04:41:54Z  INFO  Backing up Git repositories ...
2023-08-02T04:41:54Z  INFO  Backing up GitHub Pages artifacts ...
2023-08-02T04:41:54Z  INFO  Backing up storage data ...
2023-08-02T04:41:54Z  INFO  Backing up custom Git hooks ...
2023-08-02T04:41:54Z  INFO  Backing up Elasticsearch indices ...
(standard_in) 1: syntax error
2023-08-02T04:42:02Z  WARN  no routes found, skipping storage backup ...
2023-08-02T04:42:06Z  INFO  Runtime: 114 seconds
2023-08-02T04:42:06Z  INFO  Completed backup of 10.0.0.6:122 in snapshot 20230802T044012 at 04:42:06
2023-08-02T04:42:06Z  INFO  Checking for leaked ssh keys ...
2023-08-02T04:42:06Z  INFO  * No leaked keys found
2023-08-02T04:42:06Z  INFO  Backup of 10.0.0.6:122 finished.

**Comment by lorenzo-psa** [comment]
Hi,

For information, on our side with GHES in 3.9.2 and ghe backup utility in 3.91, we got an elasticsearch exception, too :
```
2023-08-04T03:14:39Z  INFO  Backing up custom Git hooks ...
2023-08-04T03:14:39Z  INFO  Backing up Elasticsearch indices ...
2023-08-04T11:30:54Z  INFO  Runtime: 30409 seconds
2023-08-04T11:30:54Z  INFO  Completed backup of github.psa-cloud.com:122 in snapshot 20230804T030405 at 11:30:54
2023-08-04T11:30:54Z  ERROR  Error: Snapshot incomplete. Some steps failed: , elasticsearch, .
```

Previously, with GHES in 3.8.7 and ghe backup utility in 3.8.1, it used to work like a charm.

Support is working on it, but we have this issue since July 28th 😞

**Comment by shcorbett** [comment]
@mabbashm110 thank you for all the details on this -- it looks like based on upgrading to the latest version of backup-utils your issue has been resolved?

**Comment by davidjarzebowski** [comment]
As described in [this issue](https://github.com/github/backup-utils/issues/1140), we are making changes to the backup-utils repository today.

@mabbashm110 : If you are still experiencing a problem, please contact our [support team](https://support.github.com/).
